### PR TITLE
feat: add github actions to sync and release wheel

### PR DESCRIPTION
**Pull request by jiashenC**
Need to figure out a way to test it.

### CODE REVIEW

**Comment by gaurav274** [comment]
Can we skip the Pypi stage and test it on a fork?

**Comment by jiashenC** [comment]
> Can we skip the Pypi stage and test it on a fork?

Verified the `Sync` workflow works that once the version file is updated, it will automatically sync `master` and `staging`.

The `Release` workflow will be triggered when `Sync` completes successfully. A `.pypirc` file is created but the last make wheel step is skipped for verification.

**Comment by xzdandy** [comment]
Could we update the documentation on how does the release work? Thanks!

**Comment by jiashenC** [comment]
> Could we update the documentation on how does the release work? Thanks!

Added docs.

**Review by xzdandy — APPROVED** [review]

**Pull request merged**
