### PR TITLE
Removing quotes from udf_metadata_key

### PR DESCRIPTION
**Pull request by hershd23**
Replacing udf_metadata_key from string_literal to ID_LITERAL
`	modified:   evadb/parser/evadb.lark`
Removed .value from key_value_pair[0] post the change in type
`	modified:   evadb/parser/lark_visitor/_functions.py`
Replaced string key to ID_LITERAL in test query
`	modified:   test/unit_tests/parser/test_parser.py`

Solves #1010

### CODE REVIEW

**Comment by hershd23** [comment]
Once tests and all work, will go ahead and change the docs as well

**Comment by hershd23** [comment]
Ran the integration test for training the model. It parsed the query correctly and invoked training but gave the following error

```
ERROR    evadb.utils.logging_manager:plan_executor.py:182 Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_batch_norm)
Traceback (most recent call last):
  File "/home/hershd23/Desktop/evadb/evadb/executor/plan_executor.py", line 178, in execute_plan
    yield from output
  File "/home/hershd23/Desktop/evadb/evadb/executor/project_executor.py", line 34, in exec
    batch = apply_project(batch, self.target_list, self.catalog())
  File "/home/hershd23/Desktop/evadb/evadb/executor/executor_utils.py", line 42, in apply_project
    batches = [expr.evaluate(batch) for expr in project_list]
  File "/home/hershd23/Desktop/evadb/evadb/executor/executor_utils.py", line 42, in <listcomp>
    batches = [expr.evaluate(batch) for expr in project_list]
  File "/home/hershd23/Desktop/evadb/evadb/expression/function_expression.py", line 129, in evaluate
    outcomes = self._apply_function_expression(func, batch, **kwargs)
  File "/home/hershd23/Desktop/evadb/evadb/expression/function_expression.py", line 188, in _apply_function_expression
    return func_args.apply_function_expression(func)
  File "/home/hershd23/Desktop/evadb/evadb/models/storage/batch.py", line 173, in apply_function_expression
    return Batch(expr(self._frames))
  File "/home/hershd23/Desktop/evadb/evadb/udfs/abstract/abstract_udf.py", line 36, in __call__
    return self.forward(args[0])
  File "/home/hershd23/Desktop/evadb/evadb/udfs/ludwig.py", line 33, in forward
    predictions, _ = self.model.predict(frames, return_type=pd.DataFrame)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/api.py", line 895, in predict
    predictions = predictor.batch_predict(
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/predictor.py", line 142, in batch_predict
    preds = self._predict(batch)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/predictor.py", line 188, in _predict
    outputs = self._predict_on_inputs(inputs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/predictor.py", line 324, in _predict_on_inputs
    return self.dist_model(inputs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/ecd.py", line 136, in forward
    combiner_outputs = self.combine(encoder_outputs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/ecd.py", line 81, in combine
    return self.combiner(encoder_outputs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/combiners/combiners.py", line 451, in forward
    hidden, aggregated_mask, masks = self.tabnet(hidden)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/modules/tabnet_modules.py", line 113, in forward
    features = self.batch_norm(features)  # [b_s, i_s]
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
    return F.batch_norm(
  File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_batch_norm)

```

**Comment by xzdandy** [comment]
> Ran the integration test for training the model. It parsed the query correctly and invoked training but gave the following error. Creating an issue for this
> 
> ```
> ERROR    evadb.utils.logging_manager:plan_executor.py:182 Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_batch_norm)
> Traceback (most recent call last):
>   File "/home/hershd23/Desktop/evadb/evadb/executor/plan_executor.py", line 178, in execute_plan
>     yield from output
>   File "/home/hershd23/Desktop/evadb/evadb/executor/project_executor.py", line 34, in exec
>     batch = apply_project(batch, self.target_list, self.catalog())
>   File "/home/hershd23/Desktop/evadb/evadb/executor/executor_utils.py", line 42, in apply_project
>     batches = [expr.evaluate(batch) for expr in project_list]
>   File "/home/hershd23/Desktop/evadb/evadb/executor/executor_utils.py", line 42, in <listcomp>
>     batches = [expr.evaluate(batch) for expr in project_list]
>   File "/home/hershd23/Desktop/evadb/evadb/expression/function_expression.py", line 129, in evaluate
>     outcomes = self._apply_function_expression(func, batch, **kwargs)
>   File "/home/hershd23/Desktop/evadb/evadb/expression/function_expression.py", line 188, in _apply_function_expression
>     return func_args.apply_function_expression(func)
>   File "/home/hershd23/Desktop/evadb/evadb/models/storage/batch.py", line 173, in apply_function_expression
>     return Batch(expr(self._frames))
>   File "/home/hershd23/Desktop/evadb/evadb/udfs/abstract/abstract_udf.py", line 36, in __call__
>     return self.forward(args[0])
>   File "/home/hershd23/Desktop/evadb/evadb/udfs/ludwig.py", line 33, in forward
>     predictions, _ = self.model.predict(frames, return_type=pd.DataFrame)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/api.py", line 895, in predict
>     predictions = predictor.batch_predict(
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/predictor.py", line 142, in batch_predict
>     preds = self._predict(batch)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/predictor.py", line 188, in _predict
>     outputs = self._predict_on_inputs(inputs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/predictor.py", line 324, in _predict_on_inputs
>     return self.dist_model(inputs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/ecd.py", line 136, in forward
>     combiner_outputs = self.combine(encoder_outputs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/models/ecd.py", line 81, in combine
>     return self.combiner(encoder_outputs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/combiners/combiners.py", line 451, in forward
>     hidden, aggregated_mask, masks = self.tabnet(hidden)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/ludwig/modules/tabnet_modules.py", line 113, in forward
>     features = self.batch_norm(features)  # [b_s, i_s]
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 171, in forward
>     return F.batch_norm(
>   File "/home/hershd23/Desktop/evadb/env/lib/python3.10/site-packages/torch/nn/functional.py", line 2450, in batch_norm
>     return torch.batch_norm(
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_batch_norm)
> ```

Thanks for creating an issue! Do you run the experiments on ada-00 or ada-01?

**Review by xzdandy — APPROVED** [review]
PR itself looks good. Thanks!

**Comment by hershd23** [comment]
Actually I ran it on my personal machine which has a GPU card

**Comment by xzdandy** [comment]
We can merge this PR. We can investigate the GPU issue in #1028. Thanks!

**Comment by xzdandy** [comment]
Come into my mind that you may also need to update the hugging face functions.

**Comment by hershd23** [comment]
> Come into my mind that you may also need to update the hugging face functions.

Oh okay @xzdandy. Will check for that today

**Comment by hershd23** [comment]
@xzdandy @gaurav274 can you take a look at the changes, have incorporated the changes for HuggingFace UDFs as well

**Comment by hershd23** [comment]
I also see some change changes in the docs causing the docs CI to fail. Should I try to fix them (best effort) in the PR?

**Review by xzdandy — CHANGES_REQUESTED** [review]
Thanks Hersh for the contribution!

Verified on Python 3.10
- All notebook testcases passed
- test/integration_tests/long/test_model_train.py passed when running as an independent test
- 4 testcases failed when `bash script/test/test.sh -m "LONG INTEGRATION"`
```
FAILED test/integration_tests/long/test_model_train.py::ModelTrainTests::test_ludwig_automl - evadb.executor.executor_utils.ExecutorError: No best trial found. Please check if you specified the correct default metric (metric_...
FAILED test/integration_tests/long/test_udf_executor.py::UDFExecutorTest::test_should_create_udf_with_metadata - lark.exceptions.UnexpectedToken: Unexpected token Token('STRING_LITERAL', "'CACHE'") at line 6, column 19.
FAILED test/integration_tests/long/test_udf_executor.py::UDFExecutorTest::test_should_return_empty_metadata_list_if_udf_is_removed - lark.exceptions.UnexpectedToken: Unexpected token Token('STRING_LITERAL', "'CACHE'") at line 6, column 19.
FAILED test/integration_tests/long/interfaces/relational/test_relational_api.py::RelationalAPI::test_create_udf_with_relational_api - AssertionError: "CREA[50 chars]Face 'task' 'automatic-speech-recognition' 'mo[22 chars]ase'" != "CREA[50 chars]Face TASK 'automatic...
```
A quick check at the error message indicates that `test/integration_tests/long/test_model_train.py::ModelTrainTests::test_ludwig_automl` failed because of GPU memory from other testcases are not freed.  If the error is not relevant to this PR's change, welcome to create an issue, and we will investigate separately! 

Minors: 
- remove `.lock_preprocessing` from the pr.

**Comment by hershd23** [comment]
Hi @xzdandy have made the following changes

- removed `.lock_preprocessing` which was created unknowingly
- Coverted `CACHE` and `BATCH` to UID structure in tests

For the other two issues

- I think the Ludwig issue has been separately pointed out by you in #1036, I think the issue is not unique to my PR rather an issue in itself that you yourself have pointed out
- `test_create_udf_with_relational_api` is actually a little tricky. Let me try and explain the issue to you.

We have made all udf_metadata_keys into UIDs. Once parsed these are processed and ultimately stored as lowercase strings in the metadata_map. What this test is trying to do is trying to convert the query and args from the API to the QUERY itself. To solve this I need to find the query builder for this which converts the API constructs to an SQL type query. I guess @gaurav274 mentioned that there are some usecases where python API data is converted to query and then run to leverage the optimizations built on the query.

Can you point me to the query builder code. I'll try and correct this there

**Comment by hershd23** [comment]
@xzdandy made the changes can you take a look

**Comment by xzdandy** [comment]
> Are we good to go with this? Can we merge or waiting for @gaurav274 's review.

I am fixing all merge conflicts now.

**Comment by xzdandy** [comment]
> Done done, I have fixed merge conflicts

One minute to update the forecasting feature to use the new UDF syntax

**Comment by hershd23** [comment]
Thanks @xzdandy for all your help!

**Pull request merged**
