### PR TITLE
Forecasting in EVA

### PR DESCRIPTION
**Pull request by americast**
Implemented standalone forecasting in EVA (using [statsforecast](https://nixtla.github.io/statsforecast) package). You can run it via the following commands:

```sql
DROP TABLE IF EXISTS AirData;

CREATE TABLE AirData (
    unique_id TEXT(30),
    ds TEXT(30),
    y INTEGER);

LOAD CSV 'data/forecasting/air-passengers.csv' INTO AirData;

DROP UDF IF EXISTS Forecast;

CREATE UDF Forecast
FROM (SELECT unique_id, ds, y FROM AirData)
TYPE Forecasting
'predict' 'y';

SELECT Forecast(12) FROM AirData;
```
Here `Forecast(12)` signifies a horizon length of `12`.

Thanks!

### CODE REVIEW

**Comment by xzdandy** [comment]
> Implemented standalone forecasting in EVA (using [statsforecast](https://nixtla.github.io/statsforecast) package). You can run it via the following commands:
> 
> ```sql
> DROP TABLE IF EXISTS AirData;
> 
> CREATE TABLE AirData (
>     unique_id TEXT(30),
>     ds TEXT(30),
>     y INTEGER);
> 
> LOAD CSV 'data/forecasting/air-passengers.csv' INTO AirData;
> 
> DROP UDF IF EXISTS Forecast;
> 
> CREATE UDF Forecast IMPL 'evadb/udfs/forecast.py';
> 
> SELECT Forecast(unique_id, ds, y) FROM AirData;
> ```
> 
> I plan to add more features to this. Tests and documentation are still pending.
> 
> Thanks!

Hi @americast, the design looks great. Is the idea that training will be implicit here? When the user runs `SELECT Forecast(unique_id, ds, y) FROM AirData;`, EvaDB will train and forecast underlying together. The rationale is that the trained forecast model can only apply to the same data source.

**Comment by americast** [comment]
Thanks @xzdandy for your review. As of now, yes the training is implicit. Since `statsforecast` trains really fast, that should be fine. However, if we were to incorporate DL-based forecasting into this, we might want to train explicitly in the background.

**Comment by jyotigoyal09** [comment]
Hi @americast, I see you are using Forecast(unique_id, ds, y) to forecast for a single time series data. I was wondering if you have a functionality to forecast for panel data. If yes, how would you make final model selection if groups in the panel do not have same seasonality/trend pattern.

**Comment by gaurav274** [comment]
> Hi @americast, I see you are using Forecast(unique_id, ds, y) to forecast for a single time series data. I was wondering if you have a functionality to forecast for panel data. If yes, how would you make final model selection if groups in the panel do not have same seasonality/trend pattern.

Hi Jyoti, Thanks for showing interest in evadb. We are in the early phases of adding forecasting. @americast @xzdandy Thoughts?

**Comment by americast** [comment]
@xzdandy I have pushed some commits and now the training is more like the Ludwig-style (#935). The training occurs when the UDF is created and the trained model is stored using a unique model file name generated from the data. Now, whenever the UDF is called, the user only needs to specify the horizon. I have updated the commands in https://github.com/georgia-tech-db/evadb/pull/969#issue-1868192153 accordingly.

**Comment by xzdandy** [comment]
Thanks for the contribution! The implementation looks good to me at high level. 

We can add
- Add a long integration test cases to verify it worked end-to-end.
- Clean up the code (remove redundant print, redundant import)

**Comment by americast** [comment]
> Thanks for the contribution! The implementation looks good to me at high level.
> 
> We can add
> 
> * Add a long integration test cases to verify it worked end-to-end.
> * Clean up the code (remove redundant print, redundant import)

@xzdandy Thanks. I have added the test and the docs.

**Review by xzdandy — CHANGES_REQUESTED** [review]
Thanks for adding the tests and documentations. They look great.

Minor improvements. 

1. Fix the linter: `bash script/test/test.sh -m LINTER`
2. Add statsforecast dependency in setup.py
3. Install the statsforecast dependency in .cricle/config.yml, so the test will be run in long integration tests.

**Comment by americast** [comment]
> Thanks for adding the tests and documentations. They look great.
> 
> Minor improvements.
> 
> 1. Fix the linter: `bash script/test/test.sh -m LINTER`
> 2. Add statsforecast dependency in setup.py
> 3. Install the statsforecast dependency in .cricle/config.yml, so the test will be run in long integration tests.

Thanks. I have updated them. Please let me know if this looks all good.

**Review by xzdandy — APPROVED** [review]
Great work!

**Comment by americast** [comment]
> Great work! Verified the long integration test works on python3.10.

Awesome, thanks!

**Pull request merged**
