### PR TITLE
Making `Ludwig` and `HuggingFace` case insensitive

### PR DESCRIPTION
**Pull request by hershd23**
Lowercasing function_type and target string before matching so as to make it case insensitive

	modified:   evadb/binder/statement_binder.py
	modified:   evadb/executor/create_function_executor.py
	
@xzdandy @gaurav274 do we want a test for checking lowercase as well? If so exactly what should it check?

Although #1071 discusses only `Ludwig`, I saw the same behaviour in the case of `HuggingFace` as well and made that case insensitive as well

### CODE REVIEW

**Review by gaurav274 — APPROVED** [review]

**Comment by gaurav274** [comment]
Fix the linter, and we should be good to go!

**Comment by xzdandy** [comment]
Just some thoughts: maybe a generic until function that does case insensitive string equality check in https://github.com/georgia-tech-db/evadb/blob/staging/evadb/utils/generic_utils.py can improve clarity and simplify the code base.

**Comment by hershd23** [comment]
Makes sense @xzdandy

**Comment by hershd23** [comment]
Facing a couple of weird issues here 

Unit tests failing where I see all test cases as passed. I do see some skipped however
```
SKIPPED [3] test/unit_tests/test_eva_cmd_client.py: unconditional skip
SKIPPED [1] test/unit_tests/executor/test_plan_executor.py:225: disk_based_storage_deprecated
SKIPPED [1] test/unit_tests/parser/test_parser.py:154: Skip parser exception handling testcase, moved to binder
SKIPPED [1] test/unit_tests/server/test_configuration_file.py:26: Run only if Ray is enabledUNIT TEST CODE: --|120|-- FAILURE

Exited with code exit status 120
```

Lint tests also failed, I don't know how, I ran `black evadb` from the project root itself, the black version in the CI and my local are the same. Any suggestions @xzdandy @gaurav274 ?

I'll try syncing to staging and try again

**Comment by hershd23** [comment]
Unit test case seems to be resolved by merging staging into branch. Linter is still failing where `python script/formatting/formatter.py` is running without any errors

**Review by xzdandy — APPROVED** [review]

**Comment by xzdandy** [comment]
> Facing a couple of weird issues here
> 
> Unit tests failing where I see all test cases as passed. I do see some skipped however
> 
> ```
> SKIPPED [3] test/unit_tests/test_eva_cmd_client.py: unconditional skip
> SKIPPED [1] test/unit_tests/executor/test_plan_executor.py:225: disk_based_storage_deprecated
> SKIPPED [1] test/unit_tests/parser/test_parser.py:154: Skip parser exception handling testcase, moved to binder
> SKIPPED [1] test/unit_tests/server/test_configuration_file.py:26: Run only if Ray is enabledUNIT TEST CODE: --|120|-- FAILURE
> 
> Exited with code exit status 120
> ```
> 
> Lint tests also failed, I don't know how, I ran `black evadb` from the project root itself, the black version in the CI and my local are the same. Any suggestions @xzdandy @gaurav274 ?
> 
> I'll try syncing to staging and try again

Thanks for introducing `string_comparison_case_insensitive`!. It will be better if we can have some unit tests both for the utility function and the places that we use `string_comparison_case_insensitive`.

I have seen similar failures recently. And it seems that the unit tests are flaky now. Created issue #1098. I rerun the test, and now they are all good.

**Pull request merged**
