### PR TITLE
Revert "feat: Integrating thirdy party Slack API "

### PR DESCRIPTION
**Pull request by jiashenC**

### CODE REVIEW

**Comment by jiashenC** [comment]
Is the previous PR in a ready state?

**Comment by kaushikravichandran** [comment]
Hi @jiashenC . The previous PR does not affect any component. I merged it because Aryan has to build on those changes.

**Comment by jiashenC** [comment]
> Hi @jiashenC . The previous PR does not affect any component. I merged it because Aryan has to build on those changes. He had taken a look at the PR.

I think it would be better that you merge this into Aryan's branch first and then merge everything together into `staging`. What do you think @xzdandy?

In addition, there are several things that can be improved for this PR
1. We'd like to add unit tests for each third-party handler.
2. Please remove `slack_sdk` from `setup.py`. Instead, it can be installed based on the handler by adding a `requirements.txt`. Here is the reference https://github.com/georgia-tech-db/evadb/tree/staging/evadb/third_party/databases/postgres.

**Review by xzdandy — APPROVED** [review]

**Comment by xzdandy** [comment]
> > Hi @jiashenC . The previous PR does not affect any component. I merged it because Aryan has to build on those changes. He had taken a look at the PR.
> 
> I think it would be better that you merge this into Aryan's branch first and then merge everything together into `staging`. What do you think @xzdandy?
> 
> In addition, there are several things that can be improved for this PR
> 
> 1. We'd like to add unit tests for each third-party handler.
> 2. Please remove `slack_sdk` from `setup.py`. Instead, it can be installed based on the handler by adding a `requirements.txt`. Here is the reference https://github.com/georgia-tech-db/evadb/tree/staging/evadb/third_party/databases/postgres.

Yes I agree. Let's only merge the fully ready PR to staging.

**Pull request merged**
