### PR TITLE
feat: select from native database

### PR DESCRIPTION
**Pull request by jiashenC**

### CODE REVIEW

**Comment by jiashenC** [comment]
@xzdandy @gaurav274 Can you give a review of the design here? I will add more tests later.

**Comment by xzdandy** [comment]
The design looks good to me.

**Review by xzdandy — APPROVED** [review]

**Comment by xzdandy** [comment]
Could we add documentation on how to connect to existing databases and run native queries?

**Comment by jiashenC** [comment]
> Could we add documentation on how to connect to existing databases and run native queries?

I can add later once the mintify docs is merged? If I add to readdocs now. It anyway needs to be ported over again. Thoughts?

**Pull request merged**
