### PR TITLE
Remove dimensions from `TEXT` and `FLOAT`

### LINKED ISSUE #1260: `TEXT` and `FLOAT` requires dimensions compulsorily.
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar feature requests.

### Description

It might be inconvenient to provide dimensions for `FLOAT` and `TEXT` datatypes. It would be better to have them taken care of by the data storage properties.

### Use case

Instead of `FLOAT(5,7)`, users could provide just `FLOAT`.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by americast**
Users can now create a table with just `FLOAT` without providing the dimensions.

Earlier:
```sql
CREATE TABLE ETTM1 (
        date TEXT(30),
        hufl FLOAT(5,7),
        hull FLOAT(5,7),
        mufl FLOAT(5,7),
        mull FLOAT(5,7),
        lufl FLOAT(5,7),
        lull FLOAT(5,7),
        ot FLOAT(5,7));
```

Now:
```sql
CREATE TABLE ETTM1 (
        date TEXT,
        hufl FLOAT,
        hull FLOAT,
        mufl FLOAT,
        mull FLOAT,
        lufl FLOAT,
        lull FLOAT,
        ot FLOAT);
```

Fixes #1260.

### CODE REVIEW

**Review by xzdandy — CHANGES_REQUESTED** [review]
Thanks for simplifying the type specification. Please fix the unit test cases: test/unit_tests/parser/test_parser.py::ParserTests::test_create_table_statement

**Comment by americast** [comment]
> Thanks for simplifying the type specification. Please fix the unit test cases: test/unit_tests/parser/test_parser.py::ParserTests::test_create_table_statement

Thanks @xzdandy. Pushed a fix!

**Comment by xzdandy** [comment]
Hi @americast, Looks good. I will add some documentation.

**Comment by americast** [comment]
Thanks @xzdandy. Do you think there is a need to include support for backward compatibility?

**Comment by xzdandy** [comment]
> Thanks @xzdandy. Do you think there is a need to include support for backward compatibility?

That's a good point. We can check if the tree has a child in the parser, and still visits it, if it has and skip if it doesn't. Thanks for thinking about backward compatibility!

**Review by xzdandy — APPROVED** [review]

**Pull request merged**
