### PR TITLE
feat: Integrating EVADB with Slack

### PR DESCRIPTION
**Pull request by aryan-rajoria**
- [x] Adding support for slack-sdk into the NativeStorageEngine
- [x] Create a new SlackStorageEngine
- [x] Convert JSON responses from slack_sdk to pandas Dataframe
- [x] Adding required binder functions to slack-handler
- [ ] Slack testcases
- [ ] Fetch query - Using select statement
- [ ] Post query - Using insert statement

### CODE REVIEW

**Comment by jarulraj** [comment]
We should move slack_sdk out of the minimal dependencies. This ensures that the base evadb can be used in many virtual environments without conflicts. And throw a message to install it if the app uses that module. \ cc @gaurav274 @jiashenC

**Comment by aryan-rajoria** [comment]
Thank you @jarulraj , I have incorporated the above point that, will be added to the next commit.
I am using a method similar to postgres database third_party requirements.txt

**Comment by kaushikravichandran** [comment]
Thanks for merging my changes to your branch directly!

**Comment by kaushikravichandran** [comment]
I am working on moving Slack related tokens to evadb.yml. Reason being we would need a token for the chatbot, one for slack and OpenAI key to get the chatbot working. This would make having tokens in the command confusing. Any thoughts?

**Comment by kaushikravichandran** [comment]
@aryan-rajoria there seems to be ~150 files touched in this PR. Are these all required? If not, can you rebase your branch to fix the spurious merge changes being picked up?

**Comment by aryan-rajoria** [comment]
@kaushikravichandran I have rebased from the staging branch.
`git rebase staging`
This caused the above file changes. Please suggest how I can change this?

**Comment by aryan-rajoria** [comment]
> I am working on moving Slack related tokens to evadb.yml. Reason being we would need a token for the chatbot, one for slack and OpenAI key to get the chatbot working. This would make having tokens in the command confusing. Any thoughts?
> 

We should use `os.eviron['TOKEN'] = 'token'` this would automatically create `.env` file.

**Comment by kaushikravichandran** [comment]
Removed chatbot related changes from this PR.

**Comment by aryan-rajoria** [comment]
> Removed chatbot related changes from this PR. @aryan-rajoria let's just focus on using slack as a data source in this PR, with support for simple SELECT/DELETE/INSERT statements.

Hi Kaushik I have already implemented a Web based API with PDF support.
Data source is not required for now.

**Comment by aryan-rajoria** [comment]
> Removed chatbot related changes from this PR. @aryan-rajoria let's just focus on using slack as a data source in this PR, with support for simple SELECT/DELETE/INSERT statements.

@kaushikravichandran I have already implemented Web api based chatbot with PDF support.
Data source is not required for now.

**Pull request closed without merging**
