### PR TITLE
[WIP] Configuration Manager Redesign

### PR DESCRIPTION
**Pull request by hershd23**
Partially solves #1140 
Adding EvaDb changes to the catalog
```
	modified:   evadb/catalog/catalog_manager.py
	new file:   evadb/catalog/models/configuration_catelog.py
	modified:   evadb/catalog/models/utils.py
	new file:   evadb/catalog/services/configuration_catalog_service.py
	modified:   evadb/catalog/sql_config.py
```
Adding EvaDB base configs to a python dict
```
	new file:   evadb/eva_config.py
```

### CODE REVIEW

**Comment by hershd23** [comment]
Up for an early review, still in WIP

**Comment by hershd23** [comment]
https://github.com/georgia-tech-db/evadb/blob/62080794c16339f52e17df74cd7956380717e95a/evadb/database.py#L35

@gaurav274 @xzdandy there is one dependency issue that I see with config. The problem with initializaing config as a table in catalog is because catalog itself depends on config as you can see in the method above. Any suggestions on what to do in order to remove this?

**Comment by xzdandy** [comment]
> https://github.com/georgia-tech-db/evadb/blob/62080794c16339f52e17df74cd7956380717e95a/evadb/database.py#L35
> 
> @gaurav274 @xzdandy there is one dependency issue that I see with config. The problem with initializaing config as a table in catalog is because catalog itself depends on config as you can see in the method above. Any suggestions on what to do in order to remove this?

At the first glance, I think we need to decouple the catalog and configuration manager. 
1) Move `catalog_database_uri` out of config, since it can not be changed once a evadb instance is created. 
2) After we move the `catalog_database_uri` out of config, we than no longer need to pass config into catalog. So we can initialize all catalog tables (including the new configuration_catalog) in the catalog manager.

**Comment by hershd23** [comment]
@xzdandy I think the dependency doesn't end there, I saw a few more examples of the dependency

**Comment by gaurav274** [comment]
Moved to #1272

**Pull request closed without merging**
