### PR TITLE
Support `SELECT expr;` which does not require `FROM table` 

### PR DESCRIPTION
**Pull request by xzdandy**
Address the `SELECT Forecast(12) FROM AirData;` to `SELECT Forecast(12);` in #1081 

- [x] update parser, binder, optimizer, and executor to allow project without children. 
- [x] update forecasting test cases and documentation.
- [x] add unit test and short integration test for `SELECT expr;`.
- [x] add documentation that we support `SELECT expr;`.

### CODE REVIEW

**Comment by xzdandy** [comment]
Discussed offline. We will send a dummy batch instead of checking `batch is None` everywhere.

**Comment by xzdandy** [comment]
@gaurav274 @jiashenC Please review. We should be ready for a forecasting notebook after this PR.

**Review by jiashenC — APPROVED** [review]
Thanks, the PR looks good to me.

Just curious about the workflow of the forecasting model for my own knowledge.

* During training (i.e., `CREATE FUNCTION`), the forecasting model reads a table and memorizes all of the data from the table to its internal state (e.g., weights). 
* During inference, the forecasting model outputs the prediction from its internal state.

Is this the reason why the `SeqScan` is no longer needed during inference?

**Comment by xzdandy** [comment]
> Thanks, the PR looks good to me.
> 
> Just curious about the workflow of the forecasting model for my own knowledge.
> 
> * During training (i.e., `CREATE FUNCTION`), the forecasting model reads a table and memorizes all of the data from the table to its internal state (e.g., weights).
> * During inference, the forecasting model outputs the prediction from its internal state.
> 
> Is this the reason why the `SeqScan` is no longer needed during inference?

Yes. It always works on the original dataset or table.

**Comment by jiashenC** [comment]
> > Thanks, the PR looks good to me.
> > Just curious about the workflow of the forecasting model for my own knowledge.
> > 
> > * During training (i.e., `CREATE FUNCTION`), the forecasting model reads a table and memorizes all of the data from the table to its internal state (e.g., weights).
> > * During inference, the forecasting model outputs the prediction from its internal state.
> > 
> > Is this the reason why the `SeqScan` is no longer needed during inference?
> 
> Yes. It always works on the original dataset or table.

I see. Then, if the user wants the same model to work with a different dataset, the user needs to call `CREATE FUNCTION` again. Is that correct?

**Comment by xzdandy** [comment]
> > > Thanks, the PR looks good to me.
> > > Just curious about the workflow of the forecasting model for my own knowledge.
> > > 
> > > * During training (i.e., `CREATE FUNCTION`), the forecasting model reads a table and memorizes all of the data from the table to its internal state (e.g., weights).
> > > * During inference, the forecasting model outputs the prediction from its internal state.
> > > 
> > > Is this the reason why the `SeqScan` is no longer needed during inference?
> > 
> > 
> > Yes. It always works on the original dataset or table.
> 
> I see. Then, if the user wants the same model to work with a different dataset, the user needs to call `CREATE FUNCTION` again. Is that correct?

That is correct. On the other hand, If I understand correctly, for forecasting, the same model can not work for other datesets. It is trained for a specific dataset. @americast who should have more knowledge in this space.

**Comment by americast** [comment]
Thanks @xzdandy for the PR aned @jiashenC for the review. Right, a function would be linked to a trained model linked to a specific dataset. Thus, while calling the function, we would not need to pass any dataset information.

**Pull request merged**
